import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Cool Learning',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/aos@2.3.4/dist/aos.css" />
      <body className={inter.className}>{children}</body>
      <script src="https://cdn.jsdelivr.net/npm/aos@2.3.4/dist/aos.css"></script>
      <script>
        AOS.init();
      </script>
    </html>
  )
}
